version: '2.1'

volumes:
    joomladb:
      driver: local
    joomla:
      driver: local

services:
  joomladb:
    image: mysql:5.7.26
    container_name: joomladb
    env_file: .env
    restart: always
    volumes:
         - joomladb:/var/lib/mysql

  joomla:
    image: trydirect/joomla:3.9.8
    build: build/joomla
    container_name: joomla
    restart: always
    env_file: .env
    links:
      - joomladb:db
    volumes:
      - ./configs/supervisord/joomla.conf:/etc/supervisord.conf
      - ./configs/php/php.ini:/etc/php/7.2/fpm/php.ini
    ports:
      - "9000"
    entrypoint: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n

  # entry point
  nginx:
    image: trydirect/nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - joomla
    ports:
      - "80:80"
    links:
      - joomla
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/nginx/conf.d:/etc/nginx/conf.d
      - ./configs/supervisord/nginx.conf:/etc/supervisor/conf.d/nginx.conf
      - ./configs/cron/nginx:/var/spool/cron/crontabs
    entrypoint: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n
